version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/portfolio
      - PORT=3000
      - JWT_SECRET=07ca2d54831393343c7a1a95e9b09f84fa3b011d9e36baa59af5b98ef5853a8416758b1c9aa46258d86b337413d4d23e51eff438dded86eed797dd3e1be158d6
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - ADMIN_EMAIL=admin@wouterkoppen.nl
    volumes:
      - ./public:/app/public
      - ./routes:/app/routes
      - ./models:/app/models
      - ./middleware:/app/middleware
      - node_modules:/app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local
  node_modules:
    driver: local